# Generated by Django 5.2.5 on 2025-08-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
